[eventSettings]

;------------------------------------------------------
; COLLECTION EVENT PRESET CONFIGURATIONS
;	only set one "true", set all or rest "false"
;------------------------------------------------------

; All maps are played on impoppable difficulty
onlyImpoppable=true

; All maps are played on easy difficulty
onlyEasy=false

; Select difficulty to not use any cash drops
noCashDrops=false

; Ignore bonus map and play only the map(s) specified in last section
ignoreEvent=false

;------------------------------------------------------
; PER MAP EVENT SETTINGS ONLY ACTIVE IF ALL PRESETS FALSE
;	switch between "easy" or "imp"
;------------------------------------------------------

; These maps use cash drops on impoppable mode

bloodypuddles=easy
darkdungeons=imp
glacialtrail=imp
trickytracks=easy
workshop=easy

; These maps do not use cash drops

darkcastle=imp
floodedvalley=imp
infernal=imp
muddypuddles=imp
ouch=imp
quad=imp
ravine=imp
sanctuary=imp

[nonEventSettings]

;------------------------------------------------------
; MAP SELECTION IF EVENT NOT ACTIVE OR NOT FOUND
;	"null", "easy", or "imp", picks random
;------------------------------------------------------

; These maps use cash drops on impoppable mode

bloodypuddles=null
darkdungeons=null
glacialtrail=null
trickytracks=null
workshop=null

; These maps do not use cash drops

darkcastle=imp
floodedvalley=null
infernal=null
muddypuddles=null
ouch=null
quad=null
ravine=null
sanctuary=null