[Settings]

;------------------------------------------------------
; PRESET CONFIGURATIONS
;	only set one "true", set all or rest "false"
;------------------------------------------------------

; All maps are played on impoppable difficulty
onlyImpoppable=true

; All maps are played on easy difficulty
onlyEasy=false

; Maps using cash drops played on easy, rest played on impoppable
noCashDrops=false

;------------------------------------------------------
; PER MAP SETTINGS ONLY ACTIVE IF ALL PRESETS ARE FALSE
;	switch between "easy" or "imp"
;------------------------------------------------------

; These maps use cash drops on impoppable mode

bloodypuddles=imp
darkdungeons=imp
glacialtrail=imp
trickytracks=easy
workshop=easy

; These maps do not use cash drops

darkcastle=imp
floodedvalley=imp
infernal=imp
muddypuddles=imp
ouch=imp
quad=imp
ravine=imp

sanctuary=imp
